### ISSUE TITLE
Update Repo folder structure to handle documentation

### ISSUE THREAD

**Issue by SimonGeering** [DevChatter/ChatterBot#20]
As the project grows we may wish to add a number of forms of documentation to it. From xml comment style help for the APIs of the Plug-In SDK to general markdown documentation and UML system diagrams. 

To help enable this I would recommend switching the project structure to mode the existing sln and associated projects into a src folder and to add a docs folder to the repo root. 

This will also be needed if we are to have a CI/CD build pipeline(s) in place as they will also need folders. 

Doing this at an early stage, before too many would-be contributors have taken forks, will be best as once more collaboration happens such major structural changes are an issue. 

On a related note it may now also be time to create a dev branch from master.

**Comment by benrick** [comment]
Regarding putting everything into a `src` folder. Yep, that's the plan to have all the `build`, `package`, `docs`, etc. folders at the same level as `src`.

**Comment by benrick** [comment]
Also want to do a rename of all of the project folders before we get too many collaborators, since that will also be hard to change once others are in there. I want to remove the bot name from all of them, since `ChatterBot` was more of a codename anyway.

**Comment by SimonGeering** [comment]
Might be an idea to temporarily stick a big header on the ReadMe letting folks know a load of re-work is pending?

**Comment by benrick** [comment]
Regarding documentation, yes, we'll want to start adding xml docs on more of the code to help module developers and collaborators. I want docs for collaboration at least to be in a `docs` folder and be linked to from the ReadMe file. It's definitely a question where user and module-builder docs should be.

**Comment by benrick** [comment]
Did the restructure and created #23 for information about the branching structure change.
