### ISSUE TITLE
Setup CI/CD Build Pipeline.

### ISSUE THREAD

**Issue by SimonGeering** [DevChatter/ChatterBot#21]
@benrick needs to make an architecture decision as to what tech stack to use for a CI/CD Build pipeline. 

I would previously have recommended Azure DevOps, but given that we are not looking to do any form of Azure deployment with this one it is not as important. So in the interests of keeping it simple and all in one place, a GitHub Actions option may suffice. 

Once a decision has been made I should be able to help get a yaml file together so there is a basic Build and Run Tests pipeline in place for every PR.

**Comment by benrick** [comment]
Had the same thought process on it, and GitHub Actions is nice for us, since everyone can find it easily. I haven't put info in it yet, but I do have a placeholder issue #9 to do this.

**Comment by SimonGeering** [comment]
@benrick can this be re-opened and myself assigned please unless you want me to use another issue for the CI/CD pipeline.

**Comment by SimonGeering** [comment]
Sorry, missed that you already had this in #9
