### ISSUE TITLE
Set Up Our Long-Term Branching Structure

### ISSUE THREAD

**Issue by benrick** [DevChatter/ChatterBot#23]
- `main` - current released version.
- `dev` - collaborative development branch for the next version. Branched from `main`. Merges into `main`.
- `release-*` - collaborative release branch for tying up final loose ends, meta-data, versions, etc. Branched from `dev`. Merged into `main` then tagged `v*.*.*.*` before `main` merged into `dev`.
- `hotfix-*` - collaborative hotfix branch for fixing issues in released version. Branched from `main`. Merged into `main` then tagged `v*.*.*.*` before `main` merged into `dev`.

**Comment by SimonGeering** [comment]
I have assumed for the CI Build pipeline for pull requests (#9) that you will want a build to happen when a PR is made into either of `main` or `dev`. If you want the others added let me know. 

I will wait for you to get this in place before I add a second phase to #9 for a build and test on completion of a merge, with a view to the need to take said build output and package those assets in a NuGet pupkg for publication or similar CD activity.

**Comment by benrick** [comment]
`dev` branch created. cc @SimonGeering
