### ISSUE TITLE
For consideration - introduction DomainModel assembly to help prevent leaking abstractions between assemblies

### ISSUE THREAD

**Issue by SimonGeering** [DevChatter/ChatterBot#31]

**Comment by SimonGeering** [comment]
Happy to do a PR for this if you want to assign it to me @benrick, if needs be we can discuss this as a draft PR first.

**Comment by SimonGeering** [comment]
### Design Decision

@benrick , as mentioned in the PR #37 it is apparent that the better solution to this, which would keep assembly names in line with namespaces and the root namespace of assemblies reflecting of their usage would be as follows:

### Option A - Repurpose the ChatterBot name:
1. Rename ChatterBot to ChatterBot.WPF or similar
2. Create a library assembly ChatterBot
3. Extract all POCOs and Interfaces from all other assemblies except the main exe into appropriate sub-folders of the ChatterBot assembly matching the namespaces of the source assembly.
4. Core would become the main domain implementation with all other dlls providing appropriate implementations as needed and DI tieing it together so everything only needs to reference the main ChatterBot assembly with the interfaces and POCOs in.

### Option B - Add a new ChatterBot.API assembly to hold POCOs and Interfaces
1. Add a new library assembly ChatterBot.API
2. Set its root namespace to ChatterBot 
3. Extract all POCOs and Interfaces from all other assemblies except the main exe into appropriate sub-folders of the ChatterBot.API assembly matching the namespaces of the source assembly.
4. Core would become the main domain implementation with all other dlls providing appropriate implementations as needed and DI tieing it together so everything only needs to reference the main ChatterBot assembly with the interfaces and POCOs in.

An example of this design can be see here <https://github.com/SimonGeering/AdminAssistant/tree/dev/src/AdminAssistant>

**Comment by benrick** [comment]
Agreed. Haven't switched project names yet, but you may notice the folder
is UI for the wpf project now.

**Comment by SimonGeering** [comment]
So rename exe to ChatterBot.UI, thereby freeing up the ChatterBot name for use as a container of interfaces and POCOs per the first option

**Comment by benrick** [comment]
Yep, I'll do another quick clean-up PR and put this in there.
